runtime: python310
automatic_scaling:
  target_cpu_utilization: 0.90
  max_instances: 1
entrypoint: gunicorn -b :8080 app:server

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 2
  failure_threshold: 2
  success_threshold: 1
  app_start_timeout_sec: 300